require 'Game.技能.技能实现.关羽.武圣'
require 'Game.技能.技能实现.关羽.武圣效果'
require 'Game.技能.技能实现.关羽.青龙怒'

require 'Game.技能.技能实现.张飞.战意'
require 'Game.技能.技能实现.张飞.黑风天煞'

require 'Game.技能.技能实现.刘备.臣服'
require 'Game.技能.技能实现.刘备.近卫术士'

require 'Game.技能.技能实现.诸葛亮.筹策'
require 'Game.技能.技能实现.诸葛亮.太极门'

require 'Game.技能.技能实现.典韦.威煞'
require 'Game.技能.技能实现.典韦.一气斩'

require 'Game.技能.技能实现.普攻.通用远程魔法'

require 'Game.技能.技能实现.流派.普攻.精粹刀锋'
require 'Game.技能.技能实现.流派.普攻.无形刀锋'
require 'Game.技能.技能实现.流派.普攻.无形刀锋效果'
require 'Game.技能.技能实现.流派.普攻.夺萃锋刃'
require 'Game.技能.技能实现.流派.普攻.回复攻击'
require 'Game.技能.技能实现.流派.普攻.护盾攻击'
require 'Game.技能.技能实现.流派.普攻.武器格挡'
require 'Game.技能.技能实现.流派.普攻.茹毛饮血'
require 'Game.技能.技能实现.流派.普攻.弱点打击'
require 'Game.技能.技能实现.流派.普攻.爆裂重击'
require 'Game.技能.技能实现.流派.普攻.爆裂重击效果'
require 'Game.技能.技能实现.流派.普攻.溅射攻击'
require 'Game.技能.技能实现.流派.普攻.顺劈斩'
require 'Game.技能.技能实现.流派.普攻.烈焰斩'
require 'Game.技能.技能实现.流派.普攻.无畏连击'
require 'Game.技能.技能实现.流派.普攻.暴力斩'
require 'Game.技能.技能实现.流派.普攻.精准反击'
require 'Game.技能.技能实现.流派.普攻.嗜血打击'
require 'Game.技能.技能实现.流派.普攻.无敌瞬斩'
require 'Game.技能.技能实现.流派.普攻.热血战魂'
require 'Game.技能.技能实现.流派.普攻.地裂波'

require 'Game.技能.技能实现.流派.暴击.劲力强化'
require 'Game.技能.技能实现.流派.暴击.无形狂暴'
require 'Game.技能.技能实现.流派.暴击.狂暴血统'
require 'Game.技能.技能实现.流派.暴击.爆裂魔力'
require 'Game.技能.技能实现.流派.暴击.爆裂回复'
require 'Game.技能.技能实现.流派.暴击.爆裂怒火'
require 'Game.技能.技能实现.流派.暴击.爆裂护盾'
require 'Game.技能.技能实现.流派.暴击.爆裂伤口'
require 'Game.技能.技能实现.流派.暴击.爆裂身躯'
require 'Game.技能.技能实现.流派.暴击.爆裂护卫'
require 'Game.技能.技能实现.流派.暴击.狂暴抑制'
require 'Game.技能.技能实现.流派.暴击.爆炸攻击'
require 'Game.技能.技能实现.流派.暴击.爆裂无双'
require 'Game.技能.技能实现.流派.暴击.爆裂魔法'
require 'Game.技能.技能实现.流派.暴击.命原爆破'
require 'Game.技能.技能实现.流派.暴击.狂暴姿态'
require 'Game.技能.技能实现.流派.暴击.狂暴姿态效果'
require 'Game.技能.技能实现.流派.暴击.战争狂热'
require 'Game.技能.技能实现.流派.暴击.至死方休'
require 'Game.技能.技能实现.流派.暴击.巨力重击'
require 'Game.技能.技能实现.流派.暴击.大爆炸'